baseURL = "https://gyhgraph.github.io"

theme = 'hugo-bearblog'

title = "Dm's Blog 🌱"
author = "Dm"
copyright = "Copyright © 2023, Dm."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true


#sectionPagesMenu = 'main'

[menu]
[[menu.main]]
    name = 'achieve'
    pageRef = '/post'
    weight = 20

[params]
  favicon = '/static/favicon.ico'

#[markup]
#  [markup.table0fContents]

